// <auto-generated />
namespace IdentityUserData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class IdentitInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdentitInit));
        
        string IMigrationMetadata.Id
        {
            get { return "201310291841558_IdentitInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
